"""empty message

Revision ID: b4c97adaad7c
Revises: 15233ca067d1
Create Date: 2024-08-06 19:33:23.866253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c97adaad7c'
down_revision = '15233ca067d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_planet_character_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='character_planet_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_planet_pkey')
    )
    # ### end Alembic commands ###
